spring:
  application:
    name: lectern-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/lectern}
    username: ${DATABASE_USERNAME:lectern}
    password: ${DATABASE_PASSWORD:lectern}
  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
